---
Name: articles
---
TheWebmen\Articles\Pages\ArticlesPage:
  defaults:
    PageLength: 1
  extensions:
    - SilverStripe\Lumberjack\Model\LumberJack

TheWebmen\Articles\Forms\ArticleCheckboxSetField:
  extensions:
    - TheWebmen\Articles\Extensions\ArticleCheckboxSetFieldExtension
